"use client";
import {NoteKeys} from './NoteKeys';
import {useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import type {Agent} from '@/lib/data/agents';
import {t,type Locale} from '@/lib/i18n/config';
import {Icons} from '@/components/ui/Icon';
export function AgentSignature({agent,index}:{agent:Agent;index:number}){
 const [tilt,setTilt]=useState({x:0,y:0}),reduced=useReducedMotion(),Icon=Icons[agent.icon];const variant=index%3;
 return <div className="sg-art" onPointerMove={e=>{if(reduced||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5});}} onPointerLeave={()=>setTilt({x:0,y:0})} aria-hidden="true"><div className="sg-art-label"><span>BEYONDEX / OBJECT {String(index+1).padStart(2,'0')}</span><span>INTERACTIVE SIGNATURE</span></div><motion.div className="sg-object" animate={{rotateY:tilt.x*20,rotateX:-tilt.y*20}} transition={{type:'spring',stiffness:100,damping:22}}><svg viewBox="0 0 420 360" fill="none"><defs><linearGradient id={'sig-'+agent.slug} x1="65" y1="0" x2="330" y2="350" gradientUnits="userSpaceOnUse"><stop stopColor="#e0f4ff"/><stop offset=".36" stopColor="var(--sg-color)"/><stop offset=".7" stopColor="#1b3066"/><stop offset="1" stopColor="#a0c6ff"/></linearGradient></defs>{Array.from({length:11},(_,i)=>variant===0?<rect key={i} x={84+i*7} y={45+i*8} width={220-i*8} height={220-i*8} rx={18+i*2} stroke={'url(#sig-'+agent.slug+')'} strokeWidth={5} transform={`rotate(${index*3+i*6} 210 180)`}/>:variant===1?<ellipse key={i} cx="210" cy="180" rx={135-i*6} ry={45+i*5} stroke={'url(#sig-'+agent.slug+')'} strokeWidth="4" transform={`rotate(${i*15+index*9} 210 180)`}/>:<path key={i} d={`M ${70+i*9} 270 Q ${80+i*3} ${20+i*10} 210 ${58+i*8} T ${350-i*9} 270`} stroke={'url(#sig-'+agent.slug+')'} strokeWidth="6" strokeLinecap="round" transform={`rotate(${i*3-15} 210 180)`}/>)}</svg><span className="sg-core"><Icon size={34}/></span></motion.div><div className="sg-art-bottom"><span>{agent.slug.toUpperCase()}</span><span>↗ {String(index+1).padStart(2,'0')} / 12</span></div></div>;
}
export function CapabilityExplorer({agent,locale}:{agent:Agent;locale:Locale}){
 const [active,setActive]=useState(0),reduced=useReducedMotion(),fa=locale==='fa';const cap=agent.capabilities[active];return <section className="sg-explorer" id="capabilities"><div className="sg-section-heading"><span className="fl-overline">02 / EXPLORE THE POSSIBILITIES</span><h2>{fa?'از نزدیک ببینید، چه کار می‌کند.':'Get closer to what it does.'}</h2><p>{fa?'یک قابلیت را انتخاب کنید و جزئیاتش را ببینید.':'Choose a capability to explore it.'}</p></div><div className="sg-explorer-grid"><div className="sg-cap-buttons" role="group" aria-label={fa?'قابلیت‌های ایجنت':'Agent capabilities'}>{agent.capabilities.map((c,i)=><button key={c.title.en} aria-pressed={active===i} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span><strong>{t(c.title,locale)}</strong><Icons.arrowUpRight size={18}/></button>)}</div><div className="sg-cap-stage"><span className="sg-stage-top">CAPABILITY / {String(active+1).padStart(2,'0')}<small>{fa?'معرفی قابلیت؛ اجرای زنده نیست':'CAPABILITY OVERVIEW · NOT A LIVE RUN'}</small></span><AnimatePresence mode="wait"><motion.div key={active} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.2}}><NoteKeys locale={locale} variant={active}/><h3>{t(cap.title,locale)}</h3><p>{t(cap.body,locale)}</p><div className="sg-cap-flow"><span>{fa?'ورودی شما':'Your input'}</span><Icons.arrowRight className="flip-rtl" size={16}/><span>{t(agent.name,locale)}</span><Icons.arrowRight className="flip-rtl" size={16}/><span>{fa?'خروجی قابل بررسی':'Reviewable output'}</span></div></motion.div></AnimatePresence></div></div></section>;
}
export function AgentTimeline({agent,locale}:{agent:Agent;locale:Locale}){
 const [active,setActive]=useState(0),fa=locale==='fa';return <section className="sg-timeline" id="agent-day"><div><span className="fl-overline">03 / A DAY WITH YOUR AGENT</span><h2>{fa?'در جریان یک روز کاری.':'A day in the workflow.'}</h2><p>{fa?'سناریوی نمونهٔ استفاده؛ برای آشنایی با روند کار.':'An illustrative scenario to explore the workflow.'}</p></div><div className="sg-timeline-body"><div className="sg-time-tabs" role="group" aria-label={fa?'مراحل روز کاری':'Workflow moments'}>{agent.dayInLife.map((step,i)=><button key={i} aria-pressed={active===i} onClick={()=>setActive(i)}><span dir="ltr">{step.time}</span><i/></button>)}</div><div className="sg-time-detail" aria-live="polite"><strong dir="ltr">{agent.dayInLife[active].time}</strong><p>{t(agent.dayInLife[active].body,locale)}</p></div></div></section>;
}

