import Link from 'next/link';
import {Logo} from './Logo';
import {Icons} from '@/components/ui/Icon';
import {localePath,type Locale} from '@/lib/i18n/config';
import type {Dictionary} from '@/lib/i18n';
import {siteConfig} from '@/lib/data/site';
export function Footer({locale}:{locale:Locale;dict:Dictionary}){
 const fa=locale==='fa';return <footer className="fl-footer"><div className="container-page"><div className="fl-footer-invite"><div><span className="fl-overline">THE NEXT CHAPTER IS YOURS / ↗</span><h2>{fa?<>برای کارهای بزرگ‌تر<br/><em>جا باز کنیم.</em></>:<>Make room<br/><em>for your next big thing.</em></>}</h2></div><Link className="fl-footer-launch" href={localePath(locale,'/contact')}><Icons.arrowUpRight size={42}/><span>{fa?'از یک گفتگو شروع کنیم':'Start a conversation'}</span></Link></div><div className="fl-footer-grid"><div><Logo locale={locale}/><p>{fa?'یک پنل اختصاصی؛ برای آدم‌هایی که می‌خواهند وقت بیشتری برای ایده‌هایشان داشته باشند.':'A dedicated workspace for people who want more time for their ideas.'}</p><a className="fl-footer-email" href={`mailto:${siteConfig.email}`} dir="ltr">{siteConfig.email}<Icons.arrowUpRight size={17}/></a></div><nav aria-label={fa?'محصولات':'Product'}><span>{fa?'فضای کار شما':'Your workspace'}</span>{[['/agents',fa?'ایجنت‌های اختصاصی':'Dedicated agents'],['/pricing',fa?'پلن‌ها و تعرفه‌ها':'Plans & pricing'],['/dashboard',fa?'تجربهٔ پنل':'Explore the panel']].map(([path,label])=><Link href={localePath(locale,path)} key={path}>{label}<Icons.arrowUpRight size={14}/></Link>)}</nav><nav aria-label={fa?'بیاندکس':'Beyondex'}><span>{fa?'پشت این تجربه':'Behind the experience'}</span><Link href={localePath(locale,'/about')}>{fa?'دربارهٔ ما':'About us'}<Icons.arrowUpRight size={14}/></Link><Link href={localePath(locale,'/contact')}>{fa?'ارتباط با ما':'Contact us'}<Icons.arrowUpRight size={14}/></Link><Link href={localePath(locale,'/lab')}>{fa?'آزمایشگاه تعامل · ۶۰ تجربه':'Interaction lab · 60 studies'}<Icons.arrowUpRight size={14}/></Link><a href="#main">{fa?'بازگشت به بالا':'Back to top'}<Icons.arrowUpRight size={14}/></a></nav></div><div className="fl-footer-word" aria-hidden="true">beyondex<span>↗</span></div><div className="fl-footer-bottom"><span>© {new Date().getFullYear()} BEYONDEX</span><span>{fa?'ساخته‌شده برای امکان‌های بیشتر.':'MADE FOR MORE POSSIBILITIES.'}</span></div></div></footer>;
}

