"use client";
import { motion,useMotionValue,useSpring,useReducedMotion } from "framer-motion";
import { useState,type ReactNode,type PointerEvent } from "react";
import Link from "next/link";
import { Icons } from "@/components/ui/Icon";
import { LogoMark } from "@/components/site/Logo";
import { localePath,type Locale } from "@/lib/i18n/config";
export function SpotlightCard({children}: {children:ReactNode}) {
 const reduced=useReducedMotion(),x=useMotionValue(0),y=useMotionValue(0),rx=useSpring(x,{stiffness:170,damping:25}),ry=useSpring(y,{stiffness:170,damping:25});
 function move(e:PointerEvent<HTMLDivElement>){if(reduced||e.pointerType!=="mouse")return;const r=e.currentTarget.getBoundingClientRect();const px=(e.clientX-r.left)/r.width,py=(e.clientY-r.top)/r.height;x.set((.5-py)*5);y.set((px-.5)*5);e.currentTarget.style.setProperty('--light-x',`${px*100}%`);e.currentTarget.style.setProperty('--light-y',`${py*100}%`);}
 return <motion.div className="ex-spotlight" onPointerMove={move} onPointerLeave={()=>{x.set(0);y.set(0);}} style={{rotateX:reduced?0:rx,rotateY:reduced?0:ry,transformPerspective:1000}}>{children}</motion.div>;
}
export function Workflow({locale}: {locale:Locale}) {
 const fa=locale==="fa",[active,setActive]=useState(0),reduced=useReducedMotion();
 const steps=fa?[
 {title:"انتخاب کنید.",body:"از فروش و محتوا تا حسابداری؛ ایجنتی را انتخاب کنید که به کار شما می‌آید.",caption:"یک همکار متناسب با کار شما",label:"انتخاب ایجنت",icon:Icons.cpu},
 {title:"متصل شوید.",body:"اشتراک ایجنت انتخابی را بررسی کنید؛ وضعیت دسترسی و تمدید در حساب بیاندکس مدیریت خواهد شد.",caption:"یک فضای کاری، با قواعد شما",label:"پنل اختصاصی",icon:Icons.layers},
 {title:"جلوتر بروید.",body:"وارد پنل مستقل همان ایجنت شوید؛ اجرای کارها و بررسی خروجی‌ها در آن محیط انجام می‌شود.",caption:"از اولین درخواست تا نتیجه",label:"بررسی نتیجه",icon:Icons.check}
 ]:[
 {title:"Find your fit.",body:"From sales and content to accounting. Choose the agent that fits your work.",caption:"A teammate built for your work",label:"Choose an agent",icon:Icons.cpu},
 {title:"Make it yours.",body:"Review your selected agent’s subscription. Access and renewals will be managed in your Beyondex account.",caption:"One workspace. Your rules.",label:"Your workspace",icon:Icons.layers},
 {title:"Move forward.",body:"Open the agent’s independent panel to perform tasks and review its output.",caption:"From your first request to a result",label:"Review results",icon:Icons.check}
 ];const step=steps[active];
 return <section className="ex-workflow" id="how"><div className="container-page"><div className="ex-section-index"><span>02 / {fa?"از ایده تا انجام":"FROM IDEA TO DONE"}</span><span>BUILT AROUND YOU ↗</span></div><div className="ex-workflow-grid"><div className="ex-workflow-copy"><span className="bx-eyebrow">{fa?"هوش مصنوعی، در جریان کار شما":"INTELLIGENCE IN YOUR WORKFLOW"}</span><h2>{fa?<>ابزارها متصل.<br/><em>شما، جلوتر.</em></>:<>Tools connected.<br/><em>You, ahead.</em></>}</h2><div className="ex-step-list" role="tablist" aria-label={fa?"مراحل شروع":"Getting started"}>{steps.map((s,i)=><button key={s.label} role="tab" id={`workflow-tab-${i}`} aria-controls="workflow-panel" aria-selected={active===i} tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let next:number|null=null;if(e.key==='ArrowDown'||e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowUp'||e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==null){e.preventDefault();setActive(next);document.getElementById(`workflow-tab-${next}`)?.focus();}}} className={active===i?'is-active':''}><span>0{i+1}</span><strong>{s.title}</strong><Icons.arrowUpRight size={18}/></button>)}</div></div><div className="ex-workflow-visual"><div className="ex-circuit" aria-hidden="true"><svg viewBox="0 0 500 330"><defs><linearGradient id="circuit-gradient"><stop stopColor="#5474ba"/><stop offset=".5" stopColor="#b4e9ff"/><stop offset="1" stopColor="#5474ba"/></linearGradient></defs><path d="M80 90H160Q180 90 180 110V155H250M420 90H340Q320 90 320 110V155H250M250 155V240Q250 260 270 260H420M250 155V240Q250 260 230 260H80"/><path className="ex-circuit-pulse" d="M80 90H160Q180 90 180 110V155H250V240Q250 260 270 260H420"/></svg><div className="ex-circuit-core"><LogoMark size={54}/><span>BEYONDEX</span></div><div className={`ex-circuit-node node-a ${active===0?'selected':''}`}><Icons.cpu size={24}/></div><div className={`ex-circuit-node node-b ${active===1?'selected':''}`}><Icons.layers size={24}/></div><div className={`ex-circuit-node node-c ${active===2?'selected':''}`}><Icons.check size={24}/></div><div className="ex-circuit-node node-d"><Icons.shield size={24}/></div></div><motion.div key={active} className="ex-workflow-detail" role="tabpanel" id="workflow-panel" aria-labelledby={`workflow-tab-${active}`} initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.3}}><span><step.icon size={17}/>{step.caption}</span><p>{step.body}</p><Link href={localePath(locale,active===0?'/agents':'/dashboard')}>{fa?(active===0?'پیدا کردن ایجنت':'دیدن پنل نمایشی'):(active===0?'Find your agent':'Explore the demo')}<Icons.arrowRight className="flip-rtl" size={16}/></Link></motion.div></div></div></div></section>;
}
