"use client";
import Link from 'next/link';
import {useState} from 'react';
import {Icons} from '@/components/ui/Icon';
import {localePath,type Locale} from '@/lib/i18n/config';
import {SectionExit} from './SectionExit';
import {BrandSculpture} from './BrandSculpture';
export function NewSections({locale}:{locale:Locale}){
 const fa=locale==='fa',[active,setActive]=useState(0);const cases=fa?[
 {name:'فروش',title:'فرصت بعدی را از دست ندهید.',body:'سرنخ‌ها را مرتب کنید، پیگیری‌ها را ببینید و پیش‌نویس ارتباط با مشتری را قبل از ارسال بررسی کنید.',slug:'sales-sdr',steps:['شناسایی فرصت','آماده‌سازی پیام','بررسی شما'],icon:Icons.target},
 {name:'بازاریابی',title:'از ایده تا یک کمپین منسجم.',body:'مخاطب، پیام و روند کمپین را در کنار هم نگه دارید؛ ایجنت ایمیل مارکتینگ را برای کارهای تکراری به کار بگیرید.',slug:'email-marketing',steps:['شناخت مخاطب','پیش‌نویس کمپین','بازبینی محتوا'],icon:Icons.mail},
 {name:'حسابداری',title:'عددها مرتب، تصمیم‌ها روشن.',body:'اطلاعات مالی را جمع‌بندی کنید و خروجی‌های ایجنت حسابداری را قبل از استفاده نهایی بررسی کنید.',slug:'accounting',steps:['دریافت اطلاعات','مرتب‌سازی گزارش','بررسی خروجی'],icon:Icons.ledger}
 ]:[
 {name:'Sales',title:'Keep the next opportunity in sight.',body:'Organize leads, follow the next steps and review customer outreach before sending it.',slug:'sales-sdr',steps:['Find opportunities','Prepare a message','Your review'],icon:Icons.target},
 {name:'Marketing',title:'From an idea to a cohesive campaign.',body:'Keep your audience, message and campaign together. Put your email agent to work on repetitive tasks.',slug:'email-marketing',steps:['Know the audience','Draft the campaign','Review the content'],icon:Icons.mail},
 {name:'Accounting',title:'Clear numbers. Better decisions.',body:'Summarize your financial information and review the accounting agent’s output before using it.',slug:'accounting',steps:['Collect information','Prepare a report','Review the result'],icon:Icons.ledger}
 ];const item=cases[active];return <><section className="iv-usecases"><div className="container-page"><div className="ex-section-index"><span>03 / {fa?'در دنیای واقعی کار شما':'IN YOUR EVERYDAY WORK'}</span><span>LESS REPETITION. MORE POSSIBILITY.</span></div><div className="iv-usecase-heading"><h2>{fa?<>کار شما.<br/><em>روش تازهٔ انجامش.</em></>:<>Your work.<br/><em>A new way to do it.</em></>}</h2><div className="iv-case-tabs" role="group" aria-label={fa?'حوزهٔ کاری':'Work scenarios'}>{cases.map((c,i)=><button key={c.name} aria-pressed={active===i} onClick={()=>setActive(i)} className={active===i?'active':''}><c.icon size={18}/>{c.name}</button>)}</div></div><div className="iv-case-body"><div className="iv-case-story"><span>{fa?'یک نمونه از کاربرد ایجنت':'AN EXAMPLE AGENT WORKFLOW'}</span><h3>{item.title}</h3><p>{item.body}</p><Link href={localePath(locale,`/agents/${item.slug}`)}>{fa?'این ایجنت را بشناسید':'Meet this agent'}<Icons.arrowRight className="flip-rtl" size={17}/></Link></div><div className="iv-case-flow">{item.steps.map((step,i)=><div key={step}><span>0{i+1}</span><strong>{step}</strong>{i===2?<Icons.shield size={19}/>:<Icons.arrowRight className="flip-rtl" size={19}/>}</div>)}</div></div></div></section><section className="iv-light-manifesto"><svg className="iv-curve" viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 100V85C300 85 340 0 720 0S1140 85 1440 85V100Z"/></svg><div className="container-page iv-manifesto-grid"><div className="iv-manifesto-art"><BrandSculpture/><span>CONNECTED BY DESIGN / BEYONDEX</span></div><div><span className="iv-eyebrow">{fa?'یک فضای کاری، با امضای شما':'YOUR SPACE. YOUR SIGNATURE.'}</span><h2>{fa?<>هوش مصنوعی،<br/>با قواعد شما.</>:<>Intelligence.<br/>On your terms.</>}</h2><p>{fa?'هر ایجنت، پنل مدیریت مستقل خودش را دارد. بیاندکس فقط مرکز اشتراک، تمدید و دسترسی به این پنل‌هاست.':'Each agent has its own management panel. Beyondex is the central place for subscriptions, renewals and access to those panels.'}</p><div className="iv-manifesto-points">{[{icon:Icons.shield,label:fa?'اشتراک‌های روشن':'Clear subscriptions'},{icon:Icons.eye,label:fa?'دسترسی به پنل‌ها':'Access to your panels'},{icon:Icons.layers,label:fa?'مدیریت در یک پنل':'One place to manage it'}].map(p=><span key={p.label}><p.icon size={18}/>{p.label}</span>)}</div><Link href={localePath(locale,'/dashboard')}>{fa?'وارد تجربهٔ پنل شوید':'Explore the workspace'}<Icons.arrowUpRight size={20}/></Link></div></div><SectionExit/></section></>;
}
